home/urls.py
from django.urls import path
from . import views
from .views import add_post, like_post

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contactform, name='contactform'),
    path('university/<int:id>/', views.chat_detail_view, name='chat'),
    path('search/', views.search, name='search'),
    path('add-post/', add_post, name='add_post'),  # URL for adding a new post
    path('like-post/<int:post_id>/', like_post, name='like_post'),
]

myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls,),
    path("", include("home.urls")),
    path("auth/", include("authentication.urls")),
    path("student/", include("studentdashboard.urls")),
    path("university/", include("unidashboard.urls")),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify
from django.db import models
from django.contrib.auth.models import BaseUserManager

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)

class CustomUser(AbstractUser):
    objects = CustomUserManager()
    email = models.EmailField(unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    def save(self, *args, **kwargs):
        if not self.username:
            self.username = slugify(self.email.split('@')[0])  # Use slugified version of email prefix as username
        super().save(*args, **kwargs)

class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    USER_TYPE_CHOICES = (
        ('student', 'Student'),
        ('university', 'University'),
    )
    DEGREE_TYPE = (
        ('bachelor', 'Bachelor'),
        ('master', 'Master'),
        ('phd', 'PhD'),
    )
    user_type = models.CharField(max_length=10, choices=USER_TYPE_CHOICES, blank=True, null=True)
    full_name = models.CharField(max_length=100, blank=True, null=True)
    profile_picture = models.ImageField(upload_to='profile_pictures/', blank=True, null=True)
    college = models.CharField(max_length=100, blank=True, null=True)
    university = models.CharField(max_length=100, blank=True, null=True)
    first_course = models.CharField(max_length=100, blank=True, null=True)
    second_course = models.CharField(max_length=100, blank=True, null=True)
    third_course = models.CharField(max_length=100, blank=True, null=True) 
    nationality = models.CharField(max_length=100, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)  
    degree_type = models.CharField(max_length=10, choices=DEGREE_TYPE, blank=True, null=True) 

    def __str__(self):
        return self.user.email
    
    

home/models.py
from django.db import models
from authentication.models import CustomUser

class Company(models.Model):
    image = models.ImageField(upload_to='company/images/')
    description = models.TextField()
    
    def __str__(self):
        return self.description
    
class History(models.Model):
    image = models.ImageField(upload_to='history/images/')
    description = models.TextField()
    
    def __str__(self):
        return self.description
    
class Mission(models.Model):
    description = models.TextField()
    
    def __str__(self):
        return self.description
    
class CEO(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='ceo/images/')
    description = models.TextField()
    
    def __str__(self):
        return self.description
    
class Product(models.Model):
    description = models.TextField()
    
    def __str__(self):
        return self.description
    
class ContactForm(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    
    def __str__(self):
        return self.name
    

class UserPost(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    post_likes = models.ManyToManyField(CustomUser, related_name='likes', blank=True)
    
    def __str__(self):
        return self.content

templates/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Page</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #000;
            color: #fff;
        }

        .navbar {
            background-color: #212529;
        }

        .navbar-brand {
            color: #ffc107;
            font-size: 24px;
        }

        .navbar-nav .nav-link {
            color: #fff;
        }

        .btn-primary {
            background-color: #ffc107;
            border-color: #ffc107;
        }

        .btn-primary:hover {
            background-color: #ffca28;
            border-color: #ffca28;
        }

        h1,
        h2,
        h3,
        h4,
        h5,
        h6 {
            color: #fff;
        }

        /* Style the about section */
        .about-section {
            padding: 50px 0;
            background-color: #000;
            color: #fff;
        }

        /* Style the about content */
        .about-content {
            text-align: justify;
        }

        /* Style the image */
        .about-image {
            max-width: 100%;
            height: auto;
            border-radius: 8px;
        }

        /* Style the button */
        .btn-yellow {
            background-color: #ffc107;
            color: #000;
        }

        .thick-line {
            border-top: 10px solid rgb(255, 255, 255) !important;
            /* Adjust thickness as needed */
            margin: 20px 0 !important;
            /* Add margin for spacing */
        }
    </style>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                        <div class="col-md-2">
                            <div class="dropdown">
                                <button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenuButton"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    Account
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <li><a class="dropdown-item" href="{% url 'index' %}">Home</a></li>
                                    <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                                </ul>
                            </div>
                        </div>

                        {% else %}
                        <div class="col-md-2">
                            <a type="button" class="btn btn-warning" href="{% url 'index' %}">Home</a>
                        </div>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <section class="about-section">
        <div class="container">
            {% for com in company|slice:1 %}
            <div class="row">
                <div class="col-md-6">
                    <img src="{{com.image.url}}" alt="About Us Image" class="about-image img-fluid">
                </div>
                <div class="col-md-6">
                    <div class="about-content">
                        <h2>Company Overview</h2>
                        <br>
                        <p>
                            {{ com.description }}
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
    <hr class="thick_line">

    <section class="about-section">
        <div class="container">
            {% for com in history|slice:1 %}
            <div class="row">
                <div class="col-md-6">
                    <div class="about-content">
                        <h2>Company Overview</h2>
                        <br>
                        <p>
                            {{ com.description }}
                        </p>
                    </div>
                </div>
                <div class="col-md-6">
                    <img src="{{com.image.url}}" alt="About Us Image" class="about-image img-fluid">
                </div>
            </div>
            {% endfor %}
        </div>
    </section>

    <!-- Second Section - Courses -->
    <section id="courses" class="container py-5">
        <h2 class="text-center mb-4" style="color: rgb(255, 255, 255);">Mission and Values <br> <p style="color:rgb(255, 255, 255); font-size: large;">  <br> At our core, we are dedicated to unlocking the boundless potential within every student. Our mission is to empower individuals on their educational journey by providing unparalleled resources and guidance in discovering universities that align with their aspirations and values. Rooted in integrity, inclusivity, and innovation, we strive to cultivate a supportive community where students can explore diverse educational opportunities and embark on a path to success. Join us in shaping the future of higher education, one student at a time.</p></h2>
        <div class="container">
            <div class="row">
                {% for com in mission|slice:2 %}
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text text-white">{{com.description}}</p>
                            
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <hr>

   

    <section id="courses" class="container py-5">
        <h2 class="text-center mb-4" style="color: rgb(255, 255, 255);">Services <p style="color:rgb(255, 255, 255); font-size: large;">  <br> Welcome to our innovative platform dedicated to promoting universities and aiding students in their quest to discover the perfect educational path! Dive into our comprehensive universities database, meticulously curated to facilitate seamless exploration of courses and programs worldwide. Engage with peers and experts through our intuitive chat feature, fostering meaningful connections and exchanging invaluable insights. Utilize our powerful search functionality to navigate through a plethora of institutions, ensuring every student finds their ideal academic fit effortlessly. Join us on this exhilarating journey of educational discovery and unlock boundless opportunities for your future success.</p></h2></h2>
        <div class="container">
            <div class="row">
                {% for com in product|slice:3 %}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text text-black">{{com.description}}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

    <!-- Fourth Section - Contact -->
    <section id="contact" class="container">
        <h2 class="text-center mb-4" style="color: rgb(255, 255, 255);">Contact form</h2>
        <div class="row">
            <!-- Contact Form -->
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <form action="{% url 'contactform' %}" method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="dynamic-email" class="form-label" style="color: black;">Email
                                    address</label>
                                <input type="email" class="form-control" id="dynamic-email" name="email"
                                    placeholder="Enter your email address">
                            </div>
                            <div class="mb-3">
                                <label for="dynamic-name" class="form-label" style="color: black;">Name</label>
                                <input type="text" class="form-control" id="dynamic-name" name="name"
                                    placeholder="Enter your name">
                            </div>
                            <div class="mb-3">
                                <label for="dynamic-message" class="form-label" style="color: black;">Message</label>
                                <textarea class="form-control" id="dynamic-message" name="message" rows="3"
                                    placeholder="Enter your message"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                        {% if success_message is not none %}
                        <!-- Success message -->
                        <div class="alert alert-success mt-3" role="alert" id="success-message" style="display: none;">
                            Your message has been successfully submitted!
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer class="bg-dark text-white py-4 mt-5">
        <div class="container text-center">
            <p>&copy; 2024 University Hub. All rights reserved.</p>
        </div>
    </footer>
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

templates/chat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Enquiry Form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: black;
            color: white;
        }

        .btn-primary {
            background-color: yellow;
            border-color: yellow;
            color: black;
            font-size: 1.2rem;
            font-weight: bold;
        }

        .form-label {
            color: white;
        }

        .form-control {
            background-color: black;
            color: white;
            border-color: white;
        }

        .form-select {
            background-color: black;
            color: white;
            border-color: white;
        }

        .form-select:focus {
            border-color: white;
            box-shadow: none;
        }

        .form-select option {
            background-color: black;
            color: white;
        }

        .enquiry-list {
            background-color: black;
            color: white;
            border: 1px solid white;
            padding: 10px;
            height: 400px; /* Adjust the height */
            overflow-y: auto; /* Enable vertical scrollbar if needed */
        }

        .enquiry-item {
            margin-bottom: 10px;
        }

        .table {
            background-color: black;
            color: white;
            border-color: white;
        }

        .table th,
        .table td {
            color: white;
            border-color: white;
        }

        .table th {
            background-color: black;
            color: yellow;
            font-size: 1.2rem;
            font-weight: bold;
        }

        .table td {
            color: white !important;
            font-size: 1.1rem;
        }
    </style>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark mt-2">
        <div class="container">
            <a class="navbar-brand" href="#">{{u.name}}</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <a href="/" class="btn btn-warning">Home</a>
        </div>
    </nav>

    <hr>
     <!-- Fourth Section - Contact -->
     <section id="contact" class="container">
        <h2 class="text-center mb-4" style="color: rgb(255, 255, 255);">Enquiry</h2>
        <div class="row">
            <!-- Contact Form -->
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <form>
                            <div class="mb-3">
                                <label for="exampleInputEmail1" class="form-label" style="color: black;">Email
                                    address</label>
                                <input type="email" class="form-control" id="exampleInputEmail1"
                                    aria-describedby="emailHelp">
                            </div>
                            <div class="mb-3">
                                <label for="exampleInputName" class="form-label" style="color: black;">Name</label>
                                <input type="text" class="form-control" id="exampleInputName">
                            </div>
                            <div class="mb-3">
                                <label for="exampleInputMessage" class="form-label"
                                    style="color: black;">Message</label>
                                <textarea class="form-control" id="exampleInputMessage" rows="3"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/index2.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <header>
        <img class="logo" src="{% static 'logo.png' %}" alt="logo">
        <nav class="navbar">
            <ul class="nav_links">
                <li><a href="index.html" class="link-underline-opacity-0">Home</a></li>
                <li><a href="">Find-University</a></li>
                <li><a href="">Chat</a></li>
                <li><a href="">About</a></li>
                <li><a href="">StudentProfile</a></li>
                <li><a href="">UniversityProfile</a></li>
            </ul>
        </nav>
        <a class="btn btn-pill" href="Register.html" data-bs-toggle="modal" data-bs-target="#registerModal">
            <button>Account</button>
        </a>

        <!-- Register Modal -->
        <div class="modal fade" id="registerModal" tabindex="-1" aria-labelledby="registerModalLabel"
            aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="registerModalLabel">Choose Your Role</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="card p-2 text-center">
                            <div>
                                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/130-man-student-2.svg/2048px-130-man-student-2.svg.png"
                                    alt="Student Photo" class="img-thumbnail" style="width: 100px;">
                            </div>
                            <h5 class="card-title">Register as Student</h5>
                            <p class="card-text">Choose this option if you are a student.</p>
                            <button type="button" class="btn btn-warning">
                                <a href="{% url 'registerStudent' %}" class="text-decoration-none" style="color: black;">Signup</a>
                            </button>
                        </div>

                        <div class="card p-2 text-center">
                            <div>
                                <img src="https://www.svgrepo.com/show/115448/school.svg" alt="Student Photo"
                                    class="img-thumbnail" style="width: 100px;">
                            </div>
                            <h5 class="card-title">Register as University</h5>
                            <p class="card-text">Choose this option if you are a University.</p>
                            <button type="button" class="btn btn-warning">
                                <a href="{% url 'registerUniversity' %}" class="text-decoration-none" style="color: black;">Signup</a>
                            </button>
                        </div>
                        <div class="text-center mt-3">
                            <a href="{% url 'login' %}" class="btn btn-dark">Already have an account? Login</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        </div>
    </header>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

templates/student-register.html
<!DOCTYPE html>
{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://kit.fontawesome.com/972fba9208.js" crossorigin="anonymous"></script>
</head>

<body>
    <header>
        <a href="/">
            <img class="logo" src="{% static 'logo.png' %}" alt="logo">
        </a>
        <div class="container">
            <div class="form-box">
                <h1 id="title">Sign Up</h1>
                <form method="POST" action="{% url 'registerStudent' %}">
                    {% csrf_token %}
                    <div class="input-group">
                        <div class="input-field" id="nameField">
                            <i class="fa-solid fa-user"></i>
                            <input type="text" name="full_name" id="id_full_name" placeholder="Name" required>
                            
                        </div>
                        <div>
                            {% for error in form.full_name.errors %}
                                <span class="error-message" style="margin-top: 50px;">{{ error }}</span>
                            {% endfor %}
                        </div>
                
                        <div class="input-field">
                            <i class="fa-solid fa-envelope"></i>
                            <input type="email" name="email" id="id_email" placeholder="Email" required>
                            
                        </div>
                        <div>
                            {% for error in form.email.errors %}
                                <span class="error-message" style="margin-top: 50px;">{{ error }}</span>
                            {% endfor %}
                        </div>
                
                        <div class="input-field">
                            <i class="fa-solid fa-lock"></i>
                            <input type="password" name="password1" id="id_password1" placeholder="Password" required>
                            
                        </div>
                        <div>
                            {% for error in form.password1.errors %}
                                <span class="error-message" style="margin-top: 50px;">{{ error }}</span>
                            {% endfor %}
                        </div>
                
                        <div class="input-field">
                            <i class="fa-solid fa-lock"></i>
                            <input type="password" name="password2" id="id_password1" placeholder="Confirm Password" required>
                            
                        </div>
                        <div>
                            {% for error in form.password2.errors %}
                                <span class="error-message" style="margin-top: 50px;">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="btn-field" style="margin-top: 100px;">
                        <button type="submit">Sign up</button>
                        <button><a href="{% url 'login' %}">Sign in</a></button>
                    </div>
                </form>
                
            </div>
        </div>
    </header>
</body>

</html>

templates/university-register.html
<!DOCTYPE html>
{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://kit.fontawesome.com/972fba9208.js" crossorigin="anonymous"></script>
</head>

<body>
    <header>
        <a href="/">
            <img class="logo" src="{% static 'logo.png' %}" alt="logo">
        </a>
        <div class="container">
            <div class="form-box">
                <h1 id="title">Sign Up</h1>
                <form method="POST" action="{% url 'registerUniversity' %}">
                    {% csrf_token %}
                    <div class="input-group">
                        <div class="input-field" id="nameField">
                            <i class="fa-solid fa-user"></i>
                            <input type="text" name="full_name" id="id_full_name" placeholder="Name" required>
                            
                        </div>
                        <div>
                            {% for error in form.full_name.errors %}
                                <span class="error-message" style="margin-top: 50px;">{{ error }}</span>
                            {% endfor %}
                        </div>
                
                        <div class="input-field">
                            <i class="fa-solid fa-envelope"></i>
                            <input type="email" name="email" id="id_email" placeholder="Email" required>
                            
                        </div>
                        <div>
                            {% for error in form.email.errors %}
                                <span class="error-message" style="margin-top: 50px;">{{ error }}</span>
                            {% endfor %}
                        </div>
                
                        <div class="input-field">
                            <i class="fa-solid fa-lock"></i>
                            <input type="password" name="password1" id="id_password1" placeholder="Password" required>
                            
                        </div>
                        <div>
                            {% for error in form.password1.errors %}
                                <span class="error-message" style="margin-top: 50px;">{{ error }}</span>
                            {% endfor %}
                        </div>
                
                        <div class="input-field">
                            <i class="fa-solid fa-lock"></i>
                            <input type="password" name="password2" id="id_password1" placeholder="Confirm Password" required>
                            
                        </div>
                        <div>
                            {% for error in form.password2.errors %}
                                <span class="error-message" style="margin-top: 50px;">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="btn-field" style="margin-top: 100px;">
                        <button type="submit">Sign up</button>
                        <button><a href="{% url 'login' %}">Sign in</a></button>
                    </div>
                </form>
                
            </div>
        </div>
    </header>
</body>

</html>